language: php

php:
  - 5.6
  - 7
  - hhvm

before_script:
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
